default: &default
  dummy_1:
    type: 'cli'
    args:
      - 'dummy/main.py'
    exec: 'python3'
  dummy_2:
    type: 'cli'
    args:
      - 'dummy/main2.py'
    exec: 'python3'


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
